apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-expose-details
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-details
  template:
    metadata:
      labels:
        app: kubernetes-details
    spec:
      containers:
        - name: kubernetes-details
          image: eu.gcr.io/abdel-tech-talks-210218/kubernetes-expose-details
          ports:
            - containerPort: 8090
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName